name: Deploy by SSH git pull origin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_LOGIN }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: cd /var/www/internal/start.mw ; git reset --hard ; git pull origin ; wget "https://sms.ru/sms/send?api_id=7C35371F-E674-7810-D92D-B1E030DFD398&to=+79109759770&msg=HOMEPAGE_deploy_done" -o /dev/null